<a href="https://colab.research.google.com/github/jwgdmkj/jupiterColab/blob/master/MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

num_classes = 10
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

x_train.shape #총 60000개 이미지가 28*28의 가로세로 이미지값 지님
#MLP를 위해, 마지막 FEATURE의 AXIS를 1개로 만들어야 함.

(60000, 28, 28)

In [56]:
x_train = x_train.reshape((len(x_train), -1))
#28*28로 풀기 위해, reshpae

x_train.shape

(60000, 784)

In [57]:
y_train.shape

(60000,)

In [44]:
x_train[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [58]:
x_train = x_train.astype("float32")/255
#data를 0에서 1사이로 만듬
x_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [59]:
y_train.shape

(60000,)

In [60]:
y_train = keras.utils.to_categorical(y_train, num_classes)
"""
y값을 one-hot encoding 하고자 한다.
궁극적으로, y train shape이 (60000,10)을 하고자 한다.
[5,0,4,....]을 [0.,0.,1.,.]의 예시처럼 하고자 하는 것.
"""


'\ny값을 one-hot encoding 하고자 한다.\n궁극적으로, y train shape이 (60000,10)을 하고자 한다.\n[5,0,4,....]을 [0.,0.,1.,.]의 예시처럼 하고자 하는 것.\n'

In [61]:
y_train[:3]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [62]:
"""
x값은 60000*784, y값은 60000*10이 나와야 함
그 사이의 히든 레이어는 어떻게 할 것인가?
"""
y_train.shape

(60000, 10)

In [65]:
#feature size를 256으로 해본다. 이 땐, 앞의 레이어는 784여야 함. 784*256가 총 학습수(bias제외)
#두번째 레이어 학습 weight는 256*128
#이렇게 앞뒤 계속 맞춰나가, 최종적으론 output이 n*10이어야 하기에, 128*10
model = keras.Sequential(
    [
    keras.Input(shape = x_train.shape[-1]),
    layers.Dense(256, activation = "relu"),
    layers.Dense(128, activation = "relu"),
    layers.Dense(num_classes, activation = "softmax")
    ]
)
#파라미터는, 784*256(매트릭스 구성 가짓수) + 256(bias)
#파라미터, output shape를 얼추 파악이 가능
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 256)               200960    
_________________________________________________________________
dense_7 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_8 (Dense)              (None, 10)                1290      
Total params: 235,146
Trainable params: 235,146
Non-trainable params: 0
_________________________________________________________________


In [67]:
#클래스 10개짜리인 학습을 해야 하므로, categorical_crossentropy를 사용
#epoch = 몇 번 돌려가며 학습할 것인가?
"""
총 60000개의 이미지를, 32개를 배치사이즈로 둠은, 60000/32로, 32개씩 넣어다며 학습하겠다
즉, 1875번을 돌려 학습을 한다. 근데 실제론 1688번 학습하는데, 이는 split=0.1에서,
10%는 제하고 90%만 학습시키겠다는 뜻

학습을 하지 않은 90%분량에 대해서도, 93%의 정확도를 보여, MLP(히든 레이어 갖춘 fully-connected)
구현 성공

이를, 하우스에서 어찌 이용할것인가
input으로, 전체 데이터 셋으로 (N,80)의 문제를 푼다고 보면 된다. 이것을,
모델을 거쳐, 각 집 별로 숫자를 예측시켜야 한다.
단, 이 문제에서는 집값을 REGRESSION하기에, AXIS가 1이 되어야 한다.
이것이 Y값과 최대한 일치시키는 것이 목적.
"""
model.compile(loss = "categorical_crossentropy", optimizer = "adam", metrics = ["accuracy"])
model.fit(x_train, y_train, batch_size = 32, epochs = 1, validation_split = 0.1)

1688/1688 [==============================] - 8s 4ms/step - loss: 0.2159 - accuracy: 0.9343 - val_loss: 0.0969 - val_accuracy: 0.9700
