In [41]:
import numpy as np
import random

Q = np.zeros([16,4])
num_episodes = 1000
num_min = 10

#Q테이블의 액션 기대값이 가장 큰 액션을 선택하거나, 모든 액션의 기대값이 0 이라면 랜덤하게 액션 선택
#이 때, 액션은 0~3중 하나
def rargmax(vector):
  m = np.amax(vector) #벡터의 최대값 
  indices = np.nonzero(vector == m)[0] 
  #print(indices)
  rndm = random.choice(indices)
  return rndm

#action : 0-L, 1-D, 2-R, 3-U
#done : 도착했는지 여부
#state : 현재 위치
#new state : action을 통해 도착한 위치
def RL_step(state, action):
  reward = 0
  done = None
  new_stt = 0
  #어떤 방향으로 갔는데, 만일 Q[state, :]중 1이 존재한다면, 글로 가야한다
  #왼쪽으로 갔을 때
  if action == 0:
    new_stt = state if state%4==0 else state-1

  #아래
  elif action == 1:
    new_stt = state if state>=12 else state+4
  
  #오른
  elif action == 2:
    new_stt = state if state%4==3 else state+1

  #위로
  elif action == 3:
    new_stt = state if state < 4 else state-4

  #간 곳이 막힌 곳일 경우, 다시 돌아옴
  if new_stt == 5 or new_stt == 7 or new_stt == 11 or new_stt == 12:
    new_stt = state 
    
  #도착했을 경우, reward를 보상으로 주고 done
  if new_stt == 15:
    done = True
    reward= 1
  return new_stt, reward, done

for i in range(num_episodes):
#for i in range(num_episodes) :
  state = 0
  total_reward = 0
  done = None

  while not done:
    action = rargmax(Q[state, :]) #가장 큰 위치로 가거나, 모두 0이면 랜덤하게 간다.
    new_state, reward, done = RL_step(state, action)
    
    Q[state, action] = reward + np.max(Q[new_state, :])
    total_reward = total_reward + reward
    state = new_state

print(Q)
"""
[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
"""

[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


'\n[[0. 1. 0. 0.]\n [0. 0. 0. 0.]\n [0. 0. 0. 0.]\n [0. 0. 0. 0.]\n [0. 1. 0. 0.]\n [0. 0. 0. 0.]\n [0. 0. 0. 0.]\n [0. 0. 0. 0.]\n [0. 0. 1. 0.]\n [0. 0. 1. 0.]\n [0. 1. 0. 0.]\n [0. 0. 0. 0.]\n [0. 0. 0. 0.]\n [0. 0. 0. 0.]\n [0. 0. 1. 0.]\n [0. 0. 0. 0.]]\n'